USE CMC_Training
GO
CREATE TABLE ORDER_DETAIL(
 ID_ORDER INT,
 PRODUCT_ID INT,
 DATE_ORDER DATETIME,
 DATE_SHIP DATETIME,
 QUANTITY INT
)


CREATE TRIGGER EXAM
ON ORDER_DETAIL
INSTEAD OF INSERT
AS
DECLARE @DATE_ORDER DATETIME, @DATE_SHIP DATETIME
SELECT @DATE_ORDER=DATE_ORDER,@DATE_SHIP=DATE_SHIP FROM inserted

IF(DATEDIFF(d,@DATE_ORDER,@DATE_SHIP)<=0)
BEGIN
	PRINT'NGAY ORDER PHAI NHO HON NGAY SHIP'
	ROLLBACK TRAN
END

INSERT INTO ORDER_DETAIL(ID_ORDER,PRODUCT_ID,DATE_ORDER,DATE_SHIP, QUANTITY)
VALUES(1,2,'2-2-2017','3-2-2017',3)