export const API_URL = Object.freeze({
    API: '/api',
    LOGIN: '/oauth/token',
    RESET_PASSWORD: '/reset-password',
    CHANGE_PASSWORD: '/change-password',
    FIND_ALL: '/find-all',
    FIND_INFO: '/find-info',
    FIND_ONE: '/find-one',
    FIND_LIST: '/find-list',
    FIND_BY_NAME: '/find-by-name',
    SAVE: '/save',
    ENABLED_OR_NOT: '/enabled-or-not',
    FIND_BY_IDENTITY_CARD: '/find-by-identity-card',
    FIND_BY_EMAIL: '/find-by-email',
    FIND_DAILY_REPORT: '/find-daily-report',
    CREATE_ROOM: '/create-room',
    USER_HAS_SEEN: '/user-has-seen',
    JOIN_ROOM: '/join-room',
    SEND_MESSAGE: '/send-message',
    FIND_ALL_INTERNAL: '/find-all-internal',
    FIND_ALL_NOT_INTERNAL_IN_24H: '/find-all-not-internal-in-24h',
    FIND_ALL_NOT_INTERNAL: '/find-all-not-internal',
    FIND_ALL_NOT_INTERNAL_IN_24H_IN_CHARGE_OF_USER: '/find-all-not-internal-in-24h-in-charge-of-user',
});

export const MODEL_URL= Object.freeze({
    CATEGORY: '/category',
    ITEM: '/item',
    MATERIAL: '/material',
    MATERIAL_DAILY_REPORT: '/material-daily-report',
    ORDER: '/order',
    ORDER_STATUS: '/order-status',
    QUANTITY: '/quantity',
    ROLE: '/role',
    STAFF: '/staff',
    STORE: '/store',
    SUPPLY: '/supply',
    TIMEKEEPING: '/timekeeping',
    TIMEKEEPING_STATUS: '/timekeeping-status',
    USER: '/user',
    WORKING_CALENDER: '/working-calender',
    NOTIFICATION: '/notification-db',
    ROOM_DB: '/room-db',
    MESSAGE_DB: '/message-db',
    SENDER_DB: '/sender-db',
});

